WITH CTE AS(
 
 select
 TO_TIMESTAMP(STARTED_AT) as  STARTED_AT,
 DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
  HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
  dayofweek(TO_TIMESTAMP(STARTED_AT)) AS DAY_OF_WEEK,
  DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME,
  
  {{functionTime('STARTED_AT')}} AS SEASON

  from {{ source('demo', 'bike') }}
  where STARTED_AT != 'started_at'
)

select *
from CTE